name: env_projet2
channels:
  - defaults
dependencies:
  - plotly
  - matplotlib
  - seaborn
  - xlrd
  - scikit-learn
  - scipy
  - more-itertools
  - numpy
  - pandas
  - scikit-learn
  - streamlit
  - Pillow
  - six
  - pip
  - requests
  - pip:
    - umap-learn
    - streamlit-lottie
    - pydataset
    - umap
    - graphviz
